POST {{apiHostUrl}}/api/users/register
Content-Type: application/json

{
  "FirstName": "Allen",
  "LastName" : "Doe",
  "Email"    : "dagtef2@gmail.com",
  "Password" : "12345678Ab",
  "Gender"   : "Female",
  "DateOfBirth" : "2005-01-01", 
  "Role"     : "Doctor",
  "Phone"    : "1234567891",
  "Address"  : "Addis Ababa"
}