POST {{apiHostUrl}}/api/blogs
Content-Type: application/json

{
  "Slug":"the-importance-of-health",
  "Title":"The Importance of Health",
  "Content":"Lorem ipsum dolor amet. Lorem ipsum dolor amet. Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.",
  "Summary":"Health is wealth. Lorem ipsum dolor amet.",
  "authorId":"db1ca3d9-8f05-444e-9cf8-e8e3f20dd38e",
  "tags":["Health","Nutrition","TestTag"]
}

