POST {{apiHostUrl}}/api/blogs
Content-Type: application/json

{
  "Slug":"my-first-blog",
  "Title":"Welcome to Health Hub",
  "Content":"Lorem ipsum dolor amet. Lorem ipsum dolor amet. Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.Lorem ipsum dolor amet.",
  "Summary":"There goes your summary!",
  "authorId":"db1ca3d9-8f05-444e-9cf8-e8e3f20dd38e"
}
