POST {{apiHostUrl}}/api/appointments/book
Content-Type: application/json

{
  "DoctorId": "8d79e723-238b-4048-0b4d-08dcccd90525",
  "PatientId": "d52fdb99-c1d6-41bb-fad5-08dccda9d99e",
  "AppointmentDate": "2024-9-7",
  "AppointmentTime": "6:00",
  "AppointmentType": "InPerson"
}
